
service: serverless-chat

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:*"

plugins:
  - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: true
        noDeploy: []

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  insertTest:
    handler: handler.insertTest
    events:
      - http:
          path: insertTest
          method: get

resources:
  Resources:
      cnxsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: serverless-chat__Connections
          AttributeDefinitions:
            - AttributeName: ConnectionID
              AttributeType: S
          KeySchema:
            - AttributeName: ConnectionID
              KeyType: HASH
          ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
      msgTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: serverless-chat__Messages
          AttributeDefinitions:
            - AttributeName: Room
              AttributeType: S
            - AttributeName: Index
              AttributeType: N
          KeySchema:
            - AttributeName: Room
              KeyType: HASH
            - AttributeName: Index
              KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
