#!/bin/sh

aws dynamodb create-table \
    --table-name serverless-chat__Connections \
    --attribute-definitions file://cnxs-attr-def.json \
    --key-schema file://cnxs-key-schema.json \
    --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

